CREATE DATABASE IF NOT EXISTS librerydb ;

use librerydb;

CREATE TABLE IF NOT EXISTS post (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(400) NOT NULL,
  file TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS user (
  id INT NOT NULL AUTO_INCREMENT ,
  name VARCHAR(200) NOT NULL,
  username VARCHAR(200) NOT NULL PRIMARY KEY,
  photo TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

describe post;