GET http://localhost:3000/api/posts
### by id ↓
GET http://localhost:3000/api/posts/1
###
DELETE http://localhost:3000/api/posts/1
###
POST http://localhost:3000/api/posts
content-type: application/json

{
  "description":"1some description",
  "file":"1some file"
}
###
PUT http://localhost:3000/api/posts/3
content-type: application/json

{
  "description":"new updating description1",
  "file":"new updating file1"
}
