GET http://localhost:3000/api/posts
### by id ↓
GET http://localhost:3000/api/posts/1
###
DELETE http://localhost:3000/api/posts/1
###
POST http://localhost:3000/api/posts
content-type: application/json

{
  "description":"testing w bastos",
  "file":"https://drive.google.com/file/d/1j2prGlZnXDTsWDgkAwlJPkPU2QV0H145/view?usp=sharing",
  "idUser": 1
}
###
PUT http://localhost:3000/api/posts/1
content-type: application/json

{
  "description":"description of post 1... testing",
  "file":"https://drive.google.com/file/d/1j4_FiK_yYVc_yqxoq0p5obUzhXRjsAkL/view"
}
