GET http://localhost:3000/api/user
### by id ↓
GET http://localhost:3000/api/user/34
###
DELETE http://localhost:3000/api/user/1
###
POST http://localhost:3000/api/user
content-type: application/json

{
  "userMail":"testtt",
  "name":"testtt"
}
###
PUT http://localhost:3000/api/user/1
content-type: application/json

{
  
}
